plugins {
    id 'java'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev.legacyforge' version '2.0.91'
}

version = mod_version
group = mod_group_id

base {
    archivesName = mod_id
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenLocal()
    mavenCentral()

    maven { url = 'https://maven.minecraftforge.net/' }

    // Parchment mappings repository
    maven { url = 'https://maven.parchmentmc.org' }

    // GeckoLib
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }

    // Lodestone/Curios
    maven {
        name 'Curios maven'
        url = "https://maven.theillusivec4.top/"
    }

    // CurseMaven
    maven { url = "https://www.cursemaven.com" }
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mapping_version
    }

    // Access Transformer
    accessTransformers = [
        'src/main/resources/META-INF/accesstransformer.cfg'
    ]

    runs {
        client {
            client()
            gameDirectory = project.file('run')
        }
        server {
            server()
            gameDirectory = project.file('run')
        }
        data {
            data()
            gameDirectory = project.file('run')
            programArguments.addAll(
                    '--mod', mod_id,
                    '--all',
                    '--output', file('src/generated/resources/').absolutePath,
                    '--existing', file('src/main/resources/').absolutePath
            )
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    // Jetbrains Annotations
    compileOnly 'org.jetbrains:annotations:24.0.1'

    // Curse Maven dependencies
    modImplementation "curse.maven:geckolib-388172:5060416"
    modRuntimeOnly "curse.maven:lodestone-616457:6213794"
    modImplementation "curse.maven:lodestone-616457:6213794"
    modImplementation "curse.maven:architectury-api-419699:5137938"
    modImplementation "curse.maven:aaa-particles-979809:6616719"
}

mixin {
    // Refmaps for each SourceSet
    add sourceSets.main, 'mixins.sandworm.refmap.json'

    // Configs to add to runs and jars
    config 'mixins.sandworm.json'
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// Process Resources configuration
processResources {
    def replaceProperties = [
            minecraft_version: project.minecraft_version,
            minecraft_version_range: project.minecraft_version_range,
            forge_version: project.forge_version,
            forge_version_range: project.forge_version_range,
            loader_version_range: project.loader_version_range,
            mod_id: project.mod_id,
            mod_name: project.mod_name,
            mod_license: project.mod_license,
            mod_version: project.mod_version,
            mod_authors: project.mod_authors,
            mod_description: project.mod_description,
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/mods.toml', 'pack.mcmeta']) {
        expand replaceProperties
    }
}

// Jar manifest configuration
tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }

    finalizedBy 'reobfJar'
}

// Publishing configuration
publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}