org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

## Environment Properties

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.3
forge_version_range=[47.4.0,)
loader_version_range=[47.4,)
mapping_version=2023.09.03


## Mod Properties

mod_id=sandworm_mod
mod_name=Desert Behemoths: Sandworms!
mod_license=GNU LGPL
mod_version=1.1.2
mod_group_id=net.jelly.sandworm_mod
mod_authors=JellyCarbonara
mod_description=Adds massive Dune-like sandworms to make deserts a bit more exciting.